// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8bSn9zVHJ7TCE8Y-lLTOUuw53SkJ0AWw',
    appId: '1:112751518072:web:075123fb6c3ac1db7aa88d',
    messagingSenderId: '112751518072',
    projectId: 'save-a-bite-249f9',
    authDomain: 'save-a-bite-249f9.firebaseapp.com',
    storageBucket: 'save-a-bite-249f9.appspot.com',
    measurementId: 'G-X6HEWEBLT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwceVWx4e4iiprWij2RDi1YC5IS9CGV6s',
    appId: '1:112751518072:android:74da5fb2531cbb057aa88d',
    messagingSenderId: '112751518072',
    projectId: 'save-a-bite-249f9',
    storageBucket: 'save-a-bite-249f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK4fCQ33xM768z6wI-Ui_75cF_wsx4EFo',
    appId: '1:112751518072:ios:b4f6374530ed5e957aa88d',
    messagingSenderId: '112751518072',
    projectId: 'save-a-bite-249f9',
    storageBucket: 'save-a-bite-249f9.appspot.com',
    iosBundleId: 'com.example.saveABite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK4fCQ33xM768z6wI-Ui_75cF_wsx4EFo',
    appId: '1:112751518072:ios:b4f6374530ed5e957aa88d',
    messagingSenderId: '112751518072',
    projectId: 'save-a-bite-249f9',
    storageBucket: 'save-a-bite-249f9.appspot.com',
    iosBundleId: 'com.example.saveABite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8bSn9zVHJ7TCE8Y-lLTOUuw53SkJ0AWw',
    appId: '1:112751518072:web:85cb151d58ab4d3f7aa88d',
    messagingSenderId: '112751518072',
    projectId: 'save-a-bite-249f9',
    authDomain: 'save-a-bite-249f9.firebaseapp.com',
    storageBucket: 'save-a-bite-249f9.appspot.com',
    measurementId: 'G-D05WSF9F3J',
  );
}
